version: '3'

services:
   app:  &python
      build: 
         context: .
         dockerfile: docker/app/Dockerfile
      image: web_simple_python_api_web_dev_image
      container_name: web_simple_python_api_web_dev

      restart: always
      ports:
         # - '8019:8019'
         - '8022:8022'
      network_mode: npm_default         
      volumes:
         - ./:/app
      environment:
         - PYTHONUNBUFFERED=1
      # command: bash -c "python3 /app/manage.py makemigrations && python3 /app/manage.py migrate && python3 /app/manage.py runserver 0.0.0.0:8019"
      command: bash -c "python3 /app/manage.py makemigrations && python3 /app/manage.py migrate && python3 /app/manage.py runserver 0.0.0.0:8022"
      deploy:
         resources:
           limits:
            # memory: 32G
            memory: 16G


