# Generated by Django 3.0.12 on 2022-06-30 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishgroups',
            old_name='desciption',
            new_name='description',
        ),
    ]
