# Generated by Django 3.0.12 on 2022-06-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220629_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='decription',
        ),
    ]
